#  -*- coding: utf-8 -*-

#  -*- coding: utf-8 -*-
#
#  Copyright (C) 2020-2022 ProGeek
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

#
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

import logging

from growatt_monitor.conf import settings

log = logging.getLogger('growatt_logging')


class GrowattUtils:

    def __init__(self):
        self.block_cmd = {}
        self.recorddict = {}

        self.srv_passthru_cmd()
        self.growatt_layouts()

    def srv_passthru_cmd(self):
        """Map of commands that will not be blocked if blockcmd is set

        :return:
        """
        self.block_cmd = {
            "0103",  # announce record
            "0104",  # data record
            "0116",  # ping
            "0119",  # identify
            "0120",  # Smart Monitor Record
            "0150",  # Archived record
            "5003",  # announce record
            "5004",  # data record
            "5016",  # ping
            "5019",  # identify
            "5050",  # Archived record
            "5103",  # announce record
            "5104",  # data record
            "5116",  # ping
            "5119",  # identify
            "5150"  # Archived record
        }

    def growatt_layouts(self):
        """Decrypted protocol layout for different types of inverters

        :return:
        """

        self.recorddict = {
            "T02NNNN": {
                "decrypt": {"value": "False"},
                "pvserial": {"value": 36, "length": 10, "type": "text", "divide": 10},
                "date": {"value": 56, "divide": 10},
                "recortype1": {"value": 70, "length": 2, "type": "num", "incl": "no"},
                "recortype2": {"value": 74, "length": 2, "type": "num", "incl": "no"},
                "pvstatus": {"value": 78, "length": 2, "type": "num"},
                "pvpowerin": {"value": 82, "length": 4, "type": "num", "divide": 10},
                "pv1voltage": {"value": 90, "length": 2, "type": "num", "divide": 10},
                "pv1current": {"value": 94, "length": 2, "type": "num", "divide": 10},
                "pv1watt": {"value": 98, "length": 4, "type": "num", "divide": 10},
                "pv2voltage": {"value": 106, "length": 2, "type": "num", "divide": 10},
                "pv2current": {"value": 110, "length": 2, "type": "num", "divide": 10},
                "pv2watt": {"value": 114, "length": 4, "type": "num", "divide": 10},
                "pvpowerout": {"value": 122, "length": 4, "type": "num", "divide": 10},
                "pvfrequentie": {"value": 130, "length": 2, "type": "num", "divide": 100},
                "pvgridvoltage": {"value": 134, "length": 2, "type": "num", "divide": 10},
                "pvgridcurrent": {"value": 138, "length": 2, "type": "num", "divide": 10},
                "pvgridpower": {"value": 142, "length": 4, "type": "num", "divide": 10},
                "pvgridvoltage2": {"value": 150, "length": 2, "type": "num", "divide": 10},
                "pvgridcurrent2": {"value": 154, "length": 2, "type": "num", "divide": 10},
                "pvgridpower2": {"value": 158, "length": 4, "type": "num", "divide": 10},
                "pvgridvoltage3": {"value": 166, "length": 2, "type": "num", "divide": 10},
                "pvgridcurrent3": {"value": 170, "length": 2, "type": "num", "divide": 10},
                "pvgridpower3": {"value": 174, "length": 4, "type": "num", "divide": 10},
                "pvenergytoday": {"value": 182, "length": 4, "type": "num", "divide": 10},
                "pvenergytotal": {"value": 190, "length": 4, "type": "num", "divide": 10},
                "totworktime": {"value": 198, "length": 4, "type": "num", "divide": 7200},
                "pvtemperature": {"value": 206, "length": 2, "type": "num", "divide": 10},
                "isof": {"value": 210, "length": 2, "type": "num", "divide": 1, "incl": "no"},
                "gfcif": {"value": 214, "length": 2, "type": "num", "divide": 1, "incl": "no"},
                "dcif": {"value": 218, "length": 2, "type": "num", "divide": 1, "incl": "no"},
                "vpvfault": {"value": 222, "length": 2, "type": "num", "divide": 1, "incl": "no"},
                "vacfault": {"value": 226, "length": 2, "type": "num", "divide": 1, "incl": "no"},
                "facfault": {"value": 230, "length": 2, "type": "num", "divide": 1, "incl": "no"},
                "tmpfault": {"value": 234, "length": 2, "type": "num", "divide": 1, "incl": "no"},
                "faultcode": {"value": 238, "length": 2, "type": "num", "divide": 1, "incl": "no"},
                "pvipmtemperature": {"value": 242, "length": 2, "type": "num", "divide": 10},
                "pbusvolt": {"value": 246, "length": 2, "type": "num", "divide": 10, "incl": "no"},
                "nbusvolt": {"value": 250, "length": 2, "type": "num", "divide": 10, "incl": "no"},
                "epv1today": {"value": 278, "length": 4, "type": "num", "divide": 10},
                "epv1total": {"value": 286, "length": 4, "type": "num", "divide": 10},
                "epv2today": {"value": 294, "length": 4, "type": "num", "divide": 10},
                "epv2total": {"value": 302, "length": 4, "type": "num", "divide": 10},
                "epvtotal": {"value": 310, "length": 4, "type": "num", "divide": 10},
                "rac": {"value": 318, "length": 4, "type": "num", "divide": 1, "incl": "no"},
                "eractoday": {"value": 326, "length": 4, "type": "num", "divide": 1, "incl": "no"},
                "eractotal": {"value": 334, "length": 4, "type": "num", "divide": 1, "incl": "no"}
            },
            "T05NNNN": {
                "decrypt": {"value": "True"},
                "pvserial": {"value": 36, "length": 10, "type": "text", "divide": 10},
                "date": {"value": 56, "divide": 10},
                "recortype1": {"value": 70, "length": 2, "type": "num", "incl": "no"},
                "recortype2": {"value": 74, "length": 2, "type": "num", "incl": "no"},
                "pvstatus": {"value": 78, "length": 2, "type": "num"},
                "pvpowerin": {"value": 82, "length": 4, "type": "num", "divide": 10},
                "pv1voltage": {"value": 90, "length": 2, "type": "num", "divide": 10},
                "pv1current": {"value": 94, "length": 2, "type": "num", "divide": 10},
                "pv1watt": {"value": 98, "length": 4, "type": "num", "divide": 10},
                "pv2voltage": {"value": 106, "length": 2, "type": "num", "divide": 10},
                "pv2current": {"value": 110, "length": 2, "type": "num", "divide": 10},
                "pv2watt": {"value": 114, "length": 4, "type": "num", "divide": 10},
                "pvpowerout": {"value": 122, "length": 4, "type": "numx", "divide": 10},
                "pvfrequentie": {"value": 130, "length": 2, "type": "num", "divide": 100},
                "pvgridvoltage": {"value": 134, "length": 2, "type": "num", "divide": 10},
                "pvgridcurrent": {"value": 138, "length": 2, "type": "num", "divide": 10},
                "pvgridpower": {"value": 142, "length": 4, "type": "num", "divide": 10},
                "pvgridvoltage2": {"value": 150, "length": 2, "type": "num", "divide": 10},
                "pvgridcurrent2": {"value": 154, "length": 2, "type": "num", "divide": 10},
                "pvgridpower2": {"value": 158, "length": 4, "type": "num", "divide": 10},
                "pvgridvoltage3": {"value": 166, "length": 2, "type": "num", "divide": 10},
                "pvgridcurrent3": {"value": 170, "length": 2, "type": "num", "divide": 10},
                "pvgridpower3": {"value": 174, "length": 4, "type": "num", "divide": 10},
                "pvenergytoday": {"value": 182, "length": 4, "type": "num", "divide": 10},
                "pvenergytotal": {"value": 190, "length": 4, "type": "num", "divide": 10},
                "totworktime": {"value": 198, "length": 4, "type": "num", "divide": 7200},
                "pvtemperature": {"value": 206, "length": 2, "type": "num", "divide": 10},
                "isof": {"value": 210, "length": 2, "type": "num", "divide": 1, "incl": "no"},
                "gfcif": {"value": 214, "length": 2, "type": "num", "divide": 1, "incl": "no"},
                "dcif": {"value": 218, "length": 2, "type": "num", "divide": 1, "incl": "no"},
                "vpvfault": {"value": 222, "length": 2, "type": "num", "divide": 1, "incl": "no"},
                "vacfault": {"value": 226, "length": 2, "type": "num", "divide": 1, "incl": "no"},
                "facfault": {"value": 230, "length": 2, "type": "num", "divide": 1, "incl": "no"},
                "tmpfault": {"value": 234, "length": 2, "type": "num", "divide": 1, "incl": "no"},
                "faultcode": {"value": 238, "length": 2, "type": "num", "divide": 1, "incl": "no"},
                "pvipmtemperature": {"value": 242, "length": 2, "type": "num", "divide": 10},
                "pbusvolt": {"value": 246, "length": 2, "type": "num", "divide": 10, "incl": "no"},
                "nbusvolt": {"value": 250, "length": 2, "type": "num", "divide": 10, "incl": "no"},
                "epv1today": {"value": 278, "length": 4, "type": "num", "divide": 10},
                "epv1total": {"value": 286, "length": 4, "type": "num", "divide": 10},
                "epv2today": {"value": 294, "length": 4, "type": "num", "divide": 10},
                "epv2total": {"value": 302, "length": 4, "type": "num", "divide": 10},
                "epvtotal": {"value": 310, "length": 4, "type": "num", "divide": 10},
                "rac": {"value": 318, "length": 4, "type": "num", "divide": 1, "incl": "no"},
                "eractoday": {"value": 326, "length": 4, "type": "num", "divide": 1, "incl": "no"},
                "eractotal": {"value": 334, "length": 4, "type": "num", "divide": 1, "incl": "no"}
            },
            "T05NNNNX": {
                "decrypt": {"value": "True"},
                "pvserial": {"value": 36, "length": 10, "type": "text", "divide": 10},
                "date": {"value": 56, "divide": 10},
                "recortype1": {"value": 70, "length": 2, "type": "num", "incl": "no"},
                "recortype2": {"value": 74, "length": 2, "type": "num", "incl": "no"},
                "pvstatus": {"value": 78, "length": 2, "type": "num"},
                "pvpowerin": {"value": 82, "length": 4, "type": "num", "divide": 10},
                "pv1voltage": {"value": 90, "length": 2, "type": "num", "divide": 10},
                "pv1current": {"value": 94, "length": 2, "type": "num", "divide": 10},
                "pv1watt": {"value": 98, "length": 4, "type": "num", "divide": 10},
                "pv2voltage": {"value": 106, "length": 2, "type": "num", "divide": 10},
                "pv2current": {"value": 110, "length": 2, "type": "num", "divide": 10},
                "pv2watt": {"value": 114, "length": 4, "type": "num", "divide": 10},
                "pvpowerout": {"value": 170, "length": 4, "type": "numx", "divide": 10},
                "pvfrequentie": {"value": 178, "length": 2, "type": "num", "divide": 100},
                "pvgridvoltage": {"value": 182, "length": 2, "type": "num", "divide": 10},
                "pvgridcurrent": {"value": 186, "length": 2, "type": "num", "divide": 10},
                "pvgridpower": {"value": 190, "length": 4, "type": "num", "divide": 10},
                "pvgridvoltage2": {"value": 198, "length": 2, "type": "num", "divide": 10},
                "pvgridcurrent2": {"value": 202, "length": 2, "type": "num", "divide": 10},
                "pvgridpower2": {"value": 206, "length": 4, "type": "num", "divide": 10},
                "pvgridvoltage3": {"value": 214, "length": 2, "type": "num", "divide": 10},
                "pvgridcurrent3": {"value": 218, "length": 2, "type": "num", "divide": 10},
                "pvgridpower3": {"value": 222, "length": 4, "type": "num", "divide": 10},
                "totworktime": {"value": 266, "length": 4, "type": "num", "divide": 7200},
                "pvenergytoday": {"value": 274, "length": 4, "type": "num", "divide": 10},
                "pvenergytotal": {"value": 282, "length": 4, "type": "num", "divide": 10},
                "epvtotal": {"value": 290, "length": 4, "type": "num", "divide": 10},
                "epv1today": {"value": 298, "length": 4, "type": "num", "divide": 10},
                "epv1total": {"value": 306, "length": 4, "type": "num", "divide": 10},
                "epv2today": {"value": 314, "length": 4, "type": "num", "divide": 10},
                "epv2total": {"value": 322, "length": 4, "type": "num", "divide": 10},
                "pvtemperature": {"value": 450, "length": 2, "type": "num", "divide": 10},
                "pvipmtemperature": {"value": 466, "length": 2, "type": "num", "divide": 10},
                "pbusvolt": {"value": 470, "length": 2, "type": "num", "divide": 10, "incl": "no"},
                "nbusvolt": {"value": 474, "length": 2, "type": "num", "divide": 10, "incl": "no"}
            },
            "T06NNNN": {
                "decrypt": {"value": "True"},
                "pvserial": {"value": 76, "length": 10, "type": "text", "divide": 10},
                "date": {"value": 136, "divide": 10},
                "recortype1": {"value": 150, "length": 2, "type": "num", "incl": "yes"},
                "recortype2": {"value": 154, "length": 2, "type": "num", "incl": "yes "},
                "pvstatus": {"value": 158, "length": 2, "type": "num"},
                "pvpowerin": {"value": 162, "length": 4, "type": "num", "divide": 10},
                "pv1voltage": {"value": 170, "length": 2, "type": "num", "divide": 10},
                "pv1current": {"value": 174, "length": 2, "type": "num", "divide": 10},
                "pv1watt": {"value": 178, "length": 4, "type": "num", "divide": 10},
                "pv2voltage": {"value": 186, "length": 2, "type": "num", "divide": 10},
                "pv2current": {"value": 190, "length": 2, "type": "num", "divide": 10},
                "pv2watt": {"value": 194, "length": 4, "type": "num", "divide": 10},
                "pvpowerout": {"value": 202, "length": 4, "type": "numx", "divide": 10},
                "pvfrequentie": {"value": 210, "length": 2, "type": "num", "divide": 100},
                "pvgridvoltage": {"value": 214, "length": 2, "type": "num", "divide": 10},
                "pvgridcurrent": {"value": 218, "length": 2, "type": "num", "divide": 10},
                "pvgridpower": {"value": 222, "length": 4, "type": "num", "divide": 10},
                "pvgridvoltage2": {"value": 230, "length": 2, "type": "num", "divide": 10},
                "pvgridcurrent2": {"value": 234, "length": 2, "type": "num", "divide": 10},
                "pvgridpower2": {"value": 238, "length": 4, "type": "num", "divide": 10},
                "pvgridvoltage3": {"value": 246, "length": 2, "type": "num", "divide": 10},
                "pvgridcurrent3": {"value": 250, "length": 2, "type": "num", "divide": 10},
                "pvgridpower3": {"value": 254, "length": 4, "type": "num", "divide": 10},
                "pvenergytoday": {"value": 262, "length": 4, "type": "num", "divide": 10},
                "pvenergytotal": {"value": 270, "length": 4, "type": "num", "divide": 10},
                "totworktime": {"value": 278, "length": 4, "type": "num", "divide": 7200},
                "pvtemperature": {"value": 286, "length": 2, "type": "num", "divide": 10},
                "isof": {"value": 290, "length": 2, "type": "num", "divide": 1, "incl": "no"},
                "gfcif": {"value": 294, "length": 2, "type": "num", "divide": 1, "incl": "no"},
                "dcif": {"value": 298, "length": 2, "type": "num", "divide": 1, "incl": "no"},
                "vpvfault": {"value": 302, "length": 2, "type": "num", "divide": 1, "incl": "no"},
                "vacfault": {"value": 306, "length": 2, "type": "num", "divide": 1, "incl": "no"},
                "facfault": {"value": 310, "length": 2, "type": "num", "divide": 1, "incl": "no"},
                "tmpfault": {"value": 314, "length": 2, "type": "num", "divide": 1, "incl": "no"},
                "faultcode": {"value": 318, "length": 2, "type": "num", "divide": 1, "incl": "no"},
                "pvipmtemperature": {"value": 322, "length": 2, "type": "num", "divide": 10},
                "pbusvolt": {"value": 326, "length": 2, "type": "num", "divide": 10, "incl": "no"},
                "nbusvolt": {"value": 330, "length": 2, "type": "num", "divide": 10, "incl": "no"},
                "epv1today": {"value": 358, "length": 4, "type": "num", "divide": 10},
                "epv1total": {"value": 366, "length": 4, "type": "num", "divide": 10},
                "epv2today": {"value": 374, "length": 4, "type": "num", "divide": 10},
                "epv2total": {"value": 382, "length": 4, "type": "num", "divide": 10},
                "epvtotal": {"value": 390, "length": 4, "type": "num", "divide": 10},
            },
            "T06NNNNX": {
                "decrypt": {"value": "True"},
                "datalogserial": {"value": 16, "length": 10, "type": "text", "divide": 10, "incl": "no"},
                "pvserial": {"value": 76, "length": 10, "type": "text", "divide": 10},
                "date": {"value": 136, "divide": 10},
                "recortype1": {"value": 150, "length": 2, "type": "num", "incl": "yes"},
                "recortype2": {"value": 154, "length": 2, "type": "num", "incl": "yes"},
                "pvstatus": {"value": 158, "length": 2, "type": "num"},
                "pvpowerin": {"value": 162, "length": 4, "type": "num", "divide": 10},
                "pv1voltage": {"value": 170, "length": 2, "type": "num", "divide": 10},
                "pv1current": {"value": 174, "length": 2, "type": "num", "divide": 10},
                "pv1watt": {"value": 178, "length": 4, "type": "num", "divide": 10},
                "pv2voltage": {"value": 186, "length": 2, "type": "num", "divide": 10},
                "pv2current": {"value": 190, "length": 2, "type": "num", "divide": 10},
                "pv2watt": {"value": 194, "length": 4, "type": "num", "divide": 10},
                "pvpowerout": {"value": 250, "length": 4, "type": "numx", "divide": 10},
                "pvfrequentie": {"value": 258, "length": 2, "type": "num", "divide": 100},
                "pvgridvoltage": {"value": 262, "length": 2, "type": "num", "divide": 10},
                "pvgridcurrent": {"value": 266, "length": 2, "type": "num", "divide": 10},
                "pvgridpower": {"value": 270, "length": 4, "type": "num", "divide": 10},
                "pvgridvoltage2": {"value": 278, "length": 2, "type": "num", "divide": 10},
                "pvgridcurrent2": {"value": 282, "length": 2, "type": "num", "divide": 10},
                "pvgridpower2": {"value": 286, "length": 4, "type": "num", "divide": 10},
                "pvgridvoltage3": {"value": 294, "length": 2, "type": "num", "divide": 10},
                "pvgridcurrent3": {"value": 298, "length": 2, "type": "num", "divide": 10},
                "pvgridpower3": {"value": 302, "length": 4, "type": "num", "divide": 10},
                "totworktime": {"value": 346, "length": 4, "type": "num", "divide": 7200},
                "pvenergytoday": {"value": 354, "length": 4, "type": "num", "divide": 10},
                "pvenergytotal": {"value": 362, "length": 4, "type": "num", "divide": 10},
                "epvtotal": {"value": 370, "length": 4, "type": "num", "divide": 10},
                "epv1today": {"value": 378, "length": 4, "type": "num", "divide": 10},
                "epv1total": {"value": 386, "length": 4, "type": "num", "divide": 10},
                "epv2today": {"value": 394, "length": 4, "type": "num", "divide": 10},
                "epv2total": {"value": 402, "length": 4, "type": "num", "divide": 10},
                "pvtemperature": {"value": 530, "length": 2, "type": "num", "divide": 10},
                "pvipmtemperature": {"value": 546, "length": 2, "type": "num", "divide": 10},
                "pbusvolt": {"value": 550, "length": 2, "type": "num", "divide": 10, "incl": "no"},
                "nbusvolt": {"value": 554, "length": 2, "type": "num", "divide": 10, "incl": "no"}
            },
            "T06NNNNXSPH": {
                "decrypt": {"value": "True"},
                "pvserial": {"value": 76, "length": 10, "type": "text", "divide": 10},
                "date": {"value": 136, "divide": 10},
                "recortype1": {"value": 150, "length": 2, "type": "num", "incl": "no"},
                "recortype2": {"value": 154, "length": 2, "type": "num", "incl": "no"},
                "pvstatus": {"value": 158, "length": 2, "type": "num"},
                "pvpowerin": {"value": 162, "length": 4, "type": "num", "divide": 10},
                "pv1voltage": {"value": 170, "length": 2, "type": "num", "divide": 10},
                "pv1current": {"value": 174, "length": 2, "type": "num", "divide": 10},
                "pv1watt": {"value": 178, "length": 4, "type": "num", "divide": 10},
                "pv2voltage": {"value": 186, "length": 2, "type": "num", "divide": 10},
                "pv2current": {"value": 190, "length": 2, "type": "num", "divide": 10},
                "pv2watt": {"value": 194, "length": 4, "type": "num", "divide": 10},
                "pvpowerout": {"value": 298, "length": 4, "type": "numx", "divide": 10},
                "pvfrequentie": {"value": 306, "length": 2, "type": "num", "divide": 100},
                "pvgridvoltage": {"value": 310, "length": 2, "type": "num", "divide": 10},
                "pvgridcurrent": {"value": 314, "length": 2, "type": "num", "divide": 10},
                "pvgridpower": {"value": 318, "length": 4, "type": "num", "divide": 10},
                "pvgridvoltage2": {"value": 326, "length": 2, "type": "num", "divide": 10},
                "pvgridcurrent2": {"value": 330, "length": 2, "type": "num", "divide": 10},
                "pvgridpower2": {"value": 334, "length": 4, "type": "num", "divide": 10},
                "pvgridvoltage3": {"value": 342, "length": 2, "type": "num", "divide": 10},
                "pvgridcurrent3": {"value": 346, "length": 2, "type": "num", "divide": 10},
                "pvgridpower3": {"value": 350, "length": 4, "type": "num", "divide": 10},
                "totworktime": {"value": 386, "length": 4, "type": "num", "divide": 7200},
                "eactoday": {"value": 370, "length": 4, "type": "num", "divide": 10},
                "pvenergytoday": {"value": 370, "length": 4, "type": "num", "divide": 10},
                "eactotal": {"value": 378, "length": 4, "type": "num", "divide": 10},
                "epvtotal": {"value": 522, "length": 4, "type": "num", "divide": 10},
                "epv1today": {"value": 394, "length": 4, "type": "num", "divide": 10},
                "epv1total": {"value": 402, "length": 4, "type": "num", "divide": 10},
                "epv2today": {"value": 410, "length": 4, "type": "num", "divide": 10},
                "epv2total": {"value": 418, "length": 4, "type": "num", "divide": 10},
                "pvtemperature": {"value": 530, "length": 2, "type": "num", "divide": 10},
                "pvipmtemperature": {"value": 534, "length": 2, "type": "num", "divide": 10},
                "pvboosttemp": {"value": 538, "length": 2, "type": "num", "divide": 10},
                "bat_dsp": {"value": 546, "length": 2, "type": "num", "divide": 10},
                "pbusvolt": {"value": 550, "length": 2, "type": "num", "divide": 10, "incl": "no"},
                "#nbusvolt": {"value": 554, "length": 2, "type": "num", "divide": 10, "incl": "no"},
                "#ipf": {"value": 558, "length": 2, "type": "num", "divide": 10, "incl": "no"},
                "#realoppercent": {"value": 562, "length": 2, "type": "num", "divide": 100, "incl": "no"},
                "#opfullwatt": {"value": 566, "length": 4, "type": "num", "divide": 10, "incl": "no"},
                "#deratingmode": {"value": 574, "length": 2, "type": "num", "divide": 1, "incl": "no"},
                "eacharge_today": {"value": 606, "length": 4, "type": "num", "divide": 10},
                "eacharge_total": {"value": 614, "length": 4, "type": "num", "divide": 10},
                "batterytype": {"value": 634, "length": 2, "type": "num", "divide": 1},
                "uwsysworkmode": {"value": 666, "length": 2, "type": "num", "divide": 1},
                "systemfaultword0": {"value": 670, "length": 2, "type": "num", "divide": 1},
                "systemfaultword1": {"value": 674, "length": 2, "type": "num", "divide": 1},
                "systemfaultword2": {"value": 678, "length": 2, "type": "num", "divide": 1},
                "systemfaultword3": {"value": 682, "length": 2, "type": "num", "divide": 1},
                "systemfaultword4": {"value": 686, "length": 2, "type": "num", "divide": 1},
                "systemfaultword5": {"value": 690, "length": 2, "type": "num", "divide": 1},
                "systemfaultword6": {"value": 694, "length": 2, "type": "num", "divide": 1},
                "systemfaultword7": {"value": 698, "length": 2, "type": "num", "divide": 1},
                "pdischarge1": {"value": 702, "length": 4, "type": "num", "divide": 10},
                "p1charge1": {"value": 710, "length": 4, "type": "num", "divide": 10},
                "vbat": {"value": 718, "length": 2, "type": "num", "divide": 10},
                "SOC": {"value": 722, "length": 2, "type": "num", "divide": 100},
                "pactouserr": {"value": 726, "length": 4, "type": "num", "divide": 10},
                "#pactousers": {"value": 734, "length": 4, "type": "num", "divide": 10, "incl": "no"},
                "#pactousert": {"value": 742, "length": 4, "type": "num", "divide": 10, "incl": "no"},
                "pactousertot": {"value": 750, "length": 4, "type": "num", "divide": 10},
                "pactogridr": {"value": 758, "length": 4, "type": "num", "divide": 10},
                "#pactogrids": {"value": 766, "length": 4, "type": "num", "divide": 10, "incl": "no"},
                "#pactogridt": {"value": 774, "length": 4, "type": "num", "divide": 10, "incl": "no"},
                "pactogridtot": {"value": 782, "length": 4, "type": "num", "divide": 10},
                "plocaloadr": {"value": 790, "length": 4, "type": "num", "divide": 10},
                "#plocaloads": {"value": 798, "length": 4, "type": "num", "divide": 10, "incl": "no"},
                "#plocaloadt": {"value": 806, "length": 4, "type": "num", "divide": 10, "incl": "no"},
                "plocaloadtot": {"value": 814, "length": 4, "type": "num", "divide": 10},
                "#ipm": {"value": 822, "length": 2, "type": "num", "divide": 10, "incl": "no"},
                "#battemp": {"value": 826, "length": 2, "type": "num", "divide": 10, "incl": "no"},
                "spdspstatus": {"value": 830, "length": 2, "type": "num", "divide": 10},
                "spbusvolt": {"value": 834, "length": 2, "type": "num", "divide": 10},
                "etouser_tod": {"value": 842, "length": 4, "type": "num", "divide": 10},
                "etouser_tot": {"value": 850, "length": 4, "type": "num", "divide": 10},
                "etogrid_tod": {"value": 858, "length": 4, "type": "num", "divide": 10},
                "etogrid_tot": {"value": 866, "length": 4, "type": "num", "divide": 10},
                "edischarge1_tod": {"value": 874, "length": 4, "type": "num", "divide": 10},
                "edischarge1_tot": {"value": 882, "length": 4, "type": "num", "divide": 10},
                "eharge1_tod": {"value": 890, "length": 4, "type": "num", "divide": 10},
                "eharge1_tot": {"value": 898, "length": 4, "type": "num", "divide": 10},
                "elocalload_tod": {"value": 906, "length": 4, "type": "num", "divide": 10},
                "elocalload_tot": {"value": 914, "length": 4, "type": "num", "divide": 10}
            },
            "T05NNNNSPF": {
                "decrypt": {"value": "True"},
                "datalogserial": {"value": 16, "length": 10, "type": "text", "divide": 10, "incl": "no"},
                "pvserial": {"value": 36, "length": 10, "type": "text", "divide": 10},
                "date": {"value": 56, "divide": 10},
                "recortype1": {"value": 70, "length": 2, "type": "num", "incl": "no"},
                "recortype2": {"value": 74, "length": 2, "type": "num", "incl": "no"},
                "pvstatus": {"value": 78, "length": 2, "type": "num"},
                "vpv1": {"value": 82, "length": 2, "type": "num", "divide": 10},
                "vpv2": {"value": 86, "length": 2, "type": "num", "divide": 10},
                "ppv1": {"value": 90, "length": 4, "type": "num", "divide": 10},
                "ppv2": {"value": 98, "length": 4, "type": "num", "divide": 10},
                "buck1curr": {"value": 106, "length": 2, "type": "num", "divide": 10},
                "buck2curr": {"value": 110, "length": 2, "type": "num", "divide": 10},
                "op_watt": {"value": 114, "length": 4, "type": "num", "divide": 10},
                "pvpowerout": {"value": 114, "length": 4, "type": "num", "divide": 10},
                "op_va": {"value": 122, "length": 4, "type": "num", "divide": 10},
                "acchr_watt": {"value": 130, "length": 4, "type": "num", "divide": 10},
                "acchr_VA": {"value": 138, "length": 4, "type": "num", "divide": 10},
                "bat_Volt": {"value": 146, "length": 2, "type": "num", "divide": 100},
                "batterySoc": {"value": 150, "length": 2, "type": "num", "divide": 1},
                "bus_volt": {"value": 154, "length": 2, "type": "num", "divide": 10},
                "grid_volt": {"value": 158, "length": 2, "type": "num", "divide": 10},
                "line_freq": {"value": 162, "length": 2, "type": "num", "divide": 100},
                "outputvolt": {"value": 166, "length": 2, "type": "num", "divide": 10},
                "pvgridvoltage": {"value": 166, "length": 2, "type": "num", "divide": 10},
                "outputfreq": {"value": 170, "length": 2, "type": "num", "divide": 100},
                "invtemp": {"value": 178, "length": 2, "type": "num", "divide": 10},
                "dcdctemp": {"value": 182, "length": 2, "type": "num", "divide": 10},
                "loadpercent": {"value": 186, "length": 2, "type": "num", "divide": 10},
                "buck1_ntc": {"value": 206, "length": 2, "type": "num", "divide": 10},
                "buck2_ntc": {"value": 210, "length": 2, "type": "num", "divide": 10},
                "OP_Curr": {"value": 214, "length": 2, "type": "num", "divide": 10},
                "Inv_Curr": {"value": 218, "length": 2, "type": "num", "divide": 10},
                "AC_InWatt": {"value": 222, "length": 4, "type": "num", "divide": 10},
                "AC_InVA": {"value": 230, "length": 4, "type": "num", "divide": 10},
                "faultBit": {"value": 238, "length": 2, "type": "num", "divide": 1},
                "warningBit": {"value": 242, "length": 2, "type": "num", "divide": 1},
                "faultValue": {"value": 246, "length": 2, "type": "num", "divide": 1},
                "warningValue": {"value": 250, "length": 2, "type": "num", "divide": 1},
                "constantPowerOK": {"value": 266, "length": 2, "type": "num", "divide": 1},
                "epv1tod": {"value": 270, "length": 4, "type": "num", "divide": 10, "incl": "no"},
                "epv1tot": {"value": 278, "length": 4, "type": "num", "divide": 10, "incl": "no"},
                "epvToday": {"value": 278, "length": 4, "type": "num", "divide": 10},
                "pvenergytoday": {"value": 278, "length": 4, "type": "num", "divide": 10},
                "epv2tod": {"value": 286, "length": 4, "type": "num", "divide": 10, "incl": "no"},
                "epvTotal": {"value": 286, "length": 4, "type": "num", "divide": 10},
                "pvenergytotal": {"value": 286, "length": 4, "type": "num", "divide": 10},
                "epv2tot": {"value": 294, "length": 4, "type": "num", "divide": 10, "incl": "no"},
                "eacCharToday": {"value": 310, "length": 4, "type": "num", "divide": 10},
                "eacCharTotal": {"value": 318, "length": 4, "type": "num", "divide": 10},
                "ebatDischarToday": {"value": 326, "length": 4, "type": "num", "divide": 10},
                "ebatDischarTotal": {"value": 334, "length": 4, "type": "num", "divide": 10},
                "eacDischarToday": {"value": 342, "length": 4, "type": "num", "divide": 10},
                "eacDischarTotal": {"value": 350, "length": 4, "type": "num", "divide": 10},
                "ACCharCurr": {"value": 358, "length": 2, "type": "num", "divide": 10},
                "ACDischarWatt": {"value": 362, "length": 4, "type": "num", "divide": 10},
                "ACDischarVA": {"value": 370, "length": 4, "type": "num", "divide": 10},
                "BatDischarWatt": {"value": 378, "length": 4, "type": "num", "divide": 10},
                "BatDischarVA": {"value": 386, "length": 4, "type": "num", "divide": 10},
                "BatWatt": {"value": 394, "length": 4, "type": "numx", "divide": 10}
            },
            "T06NNNNSPF": {
                "decrypt": {"value": "True"},
                "datalogserial": {"value": 16, "length": 10, "type": "text", "divide": 10},
                "pvserial": {"value": 76, "length": 10, "type": "text", "divide": 10},
                "date": {"value": 136, "divide": 10},
                "recortype1": {"value": 150, "length": 2, "type": "num", "incl": "no"},
                "recortype2": {"value": 154, "length": 2, "type": "num", "incl": "no"},
                "pvstatus": {"value": 158, "length": 2, "type": "num"},
                "vpv1": {"value": 162, "length": 2, "type": "num", "divide": 10},
                "vpv2": {"value": 166, "length": 2, "type": "num", "divide": 10},
                "ppv1": {"value": 170, "length": 4, "type": "num", "divide": 10},
                "ppv2": {"value": 178, "length": 4, "type": "num", "divide": 10},
                "buck1curr": {"value": 186, "length": 2, "type": "num", "divide": 10},
                "buck2curr": {"value": 190, "length": 2, "type": "num", "divide": 10},
                "op_watt": {"value": 194, "length": 4, "type": "num", "divide": 10},
                "pvpowerout": {"value": 194, "length": 4, "type": "num", "divide": 10},
                "op_va": {"value": 204, "length": 4, "type": "num", "divide": 10},
                "acchr_watt": {"value": 210, "length": 4, "type": "num", "divide": 10},
                "acchr_VA": {"value": 218, "length": 4, "type": "num", "divide": 10},
                "bat_Volt": {"value": 226, "length": 2, "type": "num", "divide": 100},
                "batterySoc": {"value": 230, "length": 2, "type": "num", "divide": 1},
                "bus_volt": {"value": 234, "length": 2, "type": "num", "divide": 10},
                "grid_volt": {"value": 238, "length": 2, "type": "num", "divide": 10},
                "line_freq": {"value": 242, "length": 2, "type": "num", "divide": 100},
                "outputvolt": {"value": 246, "length": 2, "type": "num", "divide": 10},
                "pvgridvoltage": {"value": 246, "length": 2, "type": "num", "divide": 10},
                "outputfreq": {"value": 250, "length": 2, "type": "num", "divide": 100},
                "invtemp": {"value": 258, "length": 2, "type": "num", "divide": 10},
                "dcdctemp": {"value": 262, "length": 2, "type": "num", "divide": 10},
                "loadpercent": {"value": 266, "length": 2, "type": "num", "divide": 10},
                "buck1_ntc": {"value": 286, "length": 2, "type": "num", "divide": 10},
                "buck2_ntc": {"value": 290, "length": 2, "type": "num", "divide": 10},
                "OP_Curr": {"value": 294, "length": 2, "type": "num", "divide": 10},
                "Inv_Curr": {"value": 298, "length": 2, "type": "num", "divide": 10},
                "AC_InWatt": {"value": 302, "length": 4, "type": "num", "divide": 10},
                "AC_InVA": {"value": 310, "length": 4, "type": "num", "divide": 10},
                "faultBit": {"value": 318, "length": 2, "type": "num", "divide": 1},
                "warningBit": {"value": 322, "length": 2, "type": "num", "divide": 1},
                "faultValue": {"value": 326, "length": 2, "type": "num", "divide": 1},
                "warningValue": {"value": 330, "length": 2, "type": "num", "divide": 1},
                "constantPowerOK": {"value": 346, "length": 2, "type": "num", "divide": 1},
                "epvtoday": {"value": 358, "length": 4, "type": "num", "divide": 10},
                "pvenergytoday": {"value": 358, "length": 4, "type": "num", "divide": 10},
                "epvtotal": {"value": 366, "length": 4, "type": "num", "divide": 10},
                "eacCharToday": {"value": 390, "length": 4, "type": "num", "divide": 10},
                "eacCharTotal": {"value": 398, "length": 4, "type": "num", "divide": 10},
                "ebatDischarToday": {"value": 406, "length": 4, "type": "num", "divide": 10},
                "ebatDischarTotal": {"value": 414, "length": 4, "type": "num", "divide": 10},
                "eacDischarToday": {"value": 422, "length": 4, "type": "num", "divide": 10},
                "eacDischarTotal": {"value": 430, "length": 4, "type": "num", "divide": 10},
                "ACCharCurr": {"value": 438, "length": 2, "type": "num", "divide": 10},
                "ACDischarWatt": {"value": 442, "length": 4, "type": "num", "divide": 10},
                "ACDischarVA": {"value": 450, "length": 4, "type": "num", "divide": 10},
                "BatDischarWatt": {"value": 458, "length": 4, "type": "num", "divide": 10},
                "BatDischarVA": {"value": 466, "length": 4, "type": "num", "divide": 10},
                "BatWatt": {"value": 474, "length": 4, "type": "numx", "divide": 10}
            },
            "T06NNNNXTL3": {
                "decrypt": {"value": "True"},
                "datalogserial": {"value": 16, "length": 10, "type": "text", "divide": 10},
                "pvserial": {"value": 76, "length": 10, "type": "text", "divide": 10},
                "date": {"value": 136, "divide": 10},
                "recortype1": {"value": 150, "length": 2, "type": "num", "incl": "no"},
                "recortype2": {"value": 154, "length": 2, "type": "num", "incl": "no"},
                "pvstatus": {"value": 158, "length": 2, "type": "num"},
                "pvpowerin": {"value": 162, "length": 4, "type": "num", "divide": 10},
                "pv1voltage": {"value": 170, "length": 2, "type": "num", "divide": 10},
                "pv1current": {"value": 174, "length": 2, "type": "num", "divide": 10},
                "pv1watt": {"value": 178, "length": 4, "type": "num", "divide": 10},
                "pv2voltage": {"value": 186, "length": 2, "type": "num", "divide": 10},
                "pv2current": {"value": 190, "length": 2, "type": "num", "divide": 10},
                "pv2watt": {"value": 194, "length": 4, "type": "num", "divide": 10},
                "pv3voltage": {"value": 202, "length": 2, "type": "num", "divide": 10, "incl": "no"},
                "pv3current": {"value": 206, "length": 2, "type": "num", "divide": 10, "incl": "no"},
                "pv3watt": {"value": 210, "length": 4, "type": "num", "divide": 10, "incl": "no"},
                "pvpowerout": {"value": 298, "length": 4, "type": "numx", "divide": 10},
                "pvfrequentie": {"value": 306, "length": 2, "type": "num", "divide": 100},
                "pvgridvoltage": {"value": 310, "length": 2, "type": "num", "divide": 10},
                "pvgridcurrent": {"value": 314, "length": 2, "type": "num", "divide": 10},
                "pvgridpower": {"value": 318, "length": 4, "type": "num", "divide": 10},
                "pvgridvoltage2": {"value": 326, "length": 2, "type": "num", "divide": 10},
                "pvgridcurrent2": {"value": 330, "length": 2, "type": "num", "divide": 10},
                "pvgridpower2": {"value": 334, "length": 4, "type": "num", "divide": 10},
                "pvgridvoltage3": {"value": 342, "length": 2, "type": "num", "divide": 10},
                "pvgridcurrent3": {"value": 346, "length": 2, "type": "num", "divide": 10},
                "pvgridpower3": {"value": 350, "length": 4, "type": "num", "divide": 10},
                "Vac_RS": {"value": 358, "length": 2, "type": "num", "divide": 10},
                "Vac_ST": {"value": 362, "length": 2, "type": "num", "divide": 10},
                "Vac_TR": {"value": 366, "length": 2, "type": "num", "divide": 10},
                "pvenergytoday": {"value": 370, "length": 4, "type": "num", "divide": 10},
                "pvenergytotal": {"value": 378, "length": 4, "type": "num", "divide": 10},
                "totworktime": {"value": 386, "length": 4, "type": "num", "divide": 7200},
                "epv1today": {"value": 394, "length": 4, "type": "num", "divide": 10},
                "epv1total": {"value": 402, "length": 4, "type": "num", "divide": 10},
                "epv2today": {"value": 410, "length": 4, "type": "num", "divide": 10},
                "epv2total": {"value": 418, "length": 4, "type": "num", "divide": 10},
                "epvtotal": {"value": 522, "length": 4, "type": "num", "divide": 10},
                "pvtemperature": {"value": 530, "length": 2, "type": "num", "divide": 10},
                "pvipmtemperature": {"value": 534, "length": 2, "type": "num", "divide": 10},
                "pvboottemperature": {"value": 538, "length": 2, "type": "num", "divide": 10},
                "temp4": {"value": 542, "length": 2, "type": "num", "divide": 10, "incl": "no"},
                "uwBatVolt_DSP": {"value": 546, "length": 2, "type": "num", "divide": 10},
                "pbusvolt": {"value": 550, "length": 2, "type": "num", "divide": 1},
                "nbusvolt": {"value": 554, "length": 2, "type": "num", "divide": 1}
            },
            "T060120": {
                "decrypt": {"value": "True"},
                "datalogserial": {"value": 16, "length": 10, "type": "text", "divide": 10},
                "pvserial": {"value": 76, "length": 10, "type": "text", "divide": 10},
                "date": {"value": 136, "divide": 10},
                "voltage_l1": {"value": 160, "length": 4, "type": "num", "divide": 10},
                "voltage_l2": {"value": 168, "length": 4, "type": "num", "divide": 10, "incl": "no"},
                "voltage_l3": {"value": 176, "length": 4, "type": "num", "divide": 10, "incl": "no"},
                "Current_l1": {"value": 184, "length": 4, "type": "num", "divide": 10},
                "Current_l2": {"value": 192, "length": 4, "type": "num", "divide": 10, "incl": "no"},
                "Current_l3": {"value": 200, "length": 4, "type": "num", "divide": 10, "incl": "no"},
                "act_power_l1": {"value": 208, "length": 4, "type": "numx", "divide": 10},
                "act_power_l2": {"value": 216, "length": 4, "type": "numx", "divide": 10, "incl": "no"},
                "act_power_l3": {"value": 224, "length": 4, "type": "numx", "divide": 10, "incl": "no"},
                "app_power_l1": {"value": 232, "length": 4, "type": "numx", "divide": 10},
                "app_power_l2": {"value": 240, "length": 4, "type": "numx", "divide": 10, "incl": "no"},
                "app_power_l3": {"value": 248, "length": 4, "type": "numx", "divide": 10, "incl": "no"},
                "react_power_l1": {"value": 256, "length": 4, "type": "numx", "divide": 10},
                "react_power_l2": {"value": 264, "length": 4, "type": "numx", "divide": 10, "incl": "no"},
                "react_power_l3": {"value": 272, "length": 4, "type": "numx", "divide": 10, "incl": "no"},
                "powerfactor_l1": {"value": 280, "length": 4, "type": "numx", "divide": 1000},
                "powerfactor_l2": {"value": 288, "length": 4, "type": "numx", "divide": 1000, "incl": "no"},
                "powerfactor_l3": {"value": 296, "length": 4, "type": "numx", "divide": 1000, "incl": "no"},
                "pos_rev_act_power": {"value": 304, "length": 4, "type": "numx", "divide": 10},
                "pos_act_power": {"value": 304, "length": 4, "type": "numx", "divide": 10, "incl": "no"},
                "rev_act_power": {"value": 304, "length": 4, "type": "numx", "divide": 10, "incl": "no"},
                "app_power": {"value": 312, "length": 4, "type": "numx", "divide": 10},
                "react_power": {"value": 320, "length": 4, "type": "numx", "divide": 10},
                "powerfactor": {"value": 328, "length": 4, "type": "numx", "divide": 1000},
                "frequency": {"value": 336, "length": 4, "type": "num", "divide": 10},
                "L1-2_voltage": {"value": 344, "length": 4, "type": "num", "divide": 10, "incl": "no"},
                "L2-3_voltage": {"value": 352, "length": 4, "type": "num", "divide": 10, "incl": "no"},
                "L3-1_voltage": {"value": 360, "length": 4, "type": "num", "divide": 10, "incl": "no"},
                "pos_act_energy": {"value": 368, "length": 4, "type": "numx", "divide": 10},
                "rev_act_energy": {"value": 376, "length": 4, "type": "numx", "divide": 10},
                "pos_act_energy_kvar": {"value": 384, "length": 4, "type": "numx", "divide": 10, "incl": "no"},
                "rev_act_energy_kvar": {"value": 392, "length": 4, "type": "numx", "divide": 10, "incl": "no"},
                "app_energy_kvar": {"value": 400, "length": 4, "type": "numx", "divide": 10, "incl": "no"},
                "act_energy_kwh": {"value": 408, "length": 4, "type": "numx", "divide": 10, "incl": "no"},
                "react_energy_kvar": {"value": 416, "length": 4, "type": "numx", "divide": 10, "incl": "no"}
            }
        }

        if settings.DEBUG:
            log.debug("Growatt hardware layout loaded")
            for key in self.recorddict:
                log.debug("{}: {}".format(key, self.recorddict[key]))

