name: Build and run tests on a push or pull-request

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths-ignore:
      - README.md
  pull_request:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths-ignore:
      - README.md

jobs:
  run_tests:
    if: "!contains(github.event.head_commit.message, '[notest]')"
    runs-on: ubuntu-latest
    name: Setup and Runs Tests
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with isort (check only)
        run: |
          pip install isort
          isort . --check-only
      - name: Lint with black (check only)
        run: |
          pip install black
          black . --check
      - name: Lint with flake8 (check only)
        run: |
          pip install flake8
          flake8 . --count --show-source --statistics
      - name: Run test suite
        run: |
          pip install pytest
          pytest -vv -m "not integration"
      - name: Build python package
        run: |
          echo "Build package version $VERSION"
          pip install setuptools wheel
          python setup.py sdist bdist_wheel
        env:
          VERSION: ${{ steps.vars.outputs.version }}
